### ISSUE TITLE
Typo in description key

### ISSUE THREAD

**Issue by rosseljost** [sabertazimi/LaTeX-snippets#4]
In the `snippets.json` file nearly all snippets have a typo in the description key.
It says `desciption` instead of `description`.

That leads to VS code showing the "name" (i.e. the key for the snippet) instead of the description.

**Comment by sabertazimi** [comment]
fixed in v0.1.2

**Comment by singularitti** [comment]
The same error still exists in `Algorithm:State`, `Algorithm:If`, `Algorithm:For`, `Algorithm:While`, `Algorithm:Ref`.
